- src/app/demo/components/dashboards/dashboards-routing.module.ts
- src/app/demo/components/dashboards/home/home-routing.module.ts
- src/app/demo/components/dashboards/home/home.component.html
- src/app/demo/components/dashboards/home/home.component.spec.ts
- src/app/demo/components/dashboards/home/home.component.ts
- src/app/demo/components/dashboards/home/home.module.ts
- src/app/layout/app.menu.component.ts
> home component added

- src/app/demo/components/dashboards/dashboards-routing.module.ts
- src/app/demo/components/dashboards/jobs/jobs-routing.module.ts
- src/app/demo/components/dashboards/jobs/jobs.component.html
- src/app/demo/components/dashboards/jobs/jobs.component.spec.ts
- src/app/demo/components/dashboards/jobs/jobs.component.ts
- src/app/demo/components/dashboards/jobs/jobs.module.ts
- src/app/demo/components/dashboards/pre-boarding/pre-boarding-routing.module.ts
- src/app/demo/components/dashboards/pre-boarding/pre-boarding.component.html
- src/app/demo/components/dashboards/pre-boarding/pre-boarding.component.spec.ts
- src/app/demo/components/dashboards/pre-boarding/pre-boarding.component.ts
- src/app/demo/components/dashboards/pre-boarding/pre-boarding.module.ts
- src/app/demo/components/dashboards/reports/reports-routing.module.ts
- src/app/demo/components/dashboards/reports/reports.component.html
- src/app/demo/components/dashboards/reports/reports.component.spec.ts
- src/app/demo/components/dashboards/reports/reports.component.ts
- src/app/demo/components/dashboards/reports/reports.module.ts
- src/app/demo/components/dashboards/settings/settings-routing.module.ts
- src/app/demo/components/dashboards/settings/settings.component.html
- src/app/demo/components/dashboards/settings/settings.component.spec.ts
- src/app/demo/components/dashboards/settings/settings.component.ts
- src/app/demo/components/dashboards/settings/settings.module.ts
- src/app/layout/app.menu.component.ts
> sidebarcomponents  added

- src/app/app-routing.module.ts
- src/app/demo/components/auth/login/login.component.html
- src/app/demo/components/auth/login/login.component.ts
- src/app/demo/components/dashboards/dashboards-routing.module.ts
- src/app/demo/components/dashboards/loginuser/loginuser-routing.module.ts
- src/app/demo/components/dashboards/loginuser/loginuser.component.html
- src/app/demo/components/dashboards/loginuser/loginuser.component.spec.ts
- src/app/demo/components/dashboards/loginuser/loginuser.component.ts
- src/app/demo/components/dashboards/loginuser/loginuser.module.ts
- src/app/demo/components/dashboards/registeruser/registeruser-routing.module.ts
- src/app/demo/components/dashboards/registeruser/registeruser.component.html
- src/app/demo/components/dashboards/registeruser/registeruser.component.spec.ts
- src/app/demo/components/dashboards/registeruser/registeruser.component.ts
- src/app/demo/components/dashboards/registeruser/registeruser.module.ts
- src/app/layout/app.menu.component.ts
> login register components

- src/app/demo/components/dashboards/candidate/candidate.component.html
- src/app/demo/components/dashboards/candidate/candidate.component.ts
- src/app/demo/components/dashboards/candidate/candidate.module.ts
- src/app/demo/components/model/candidate.ts
> added candidate feilds

- src/app/demo/components/dashboards/recruiter/createrecruiter/createrecruiter.component.html
- src/app/demo/components/dashboards/recruiter/createrecruiter/createrecruiter.component.ts
- src/app/demo/components/model/recruiter.ts
> recruiter post api chnges

- src/app/demo/components/dashboards/talentpool/listtalentpool/listtalentpool.component.ts
- src/app/demo/components/dashboards/talentpool/talentpool.component.ts
- src/app/demo/components/model/candidate.ts
- src/app/demo/components/model/talentpool.ts
- src/app/demo/components/model/talentpoolone.ts
> talentpoollistcomponent changes

- src/app/demo/components/dashboards/candidate/createcandidate2/createcandidate2-routing.module.ts
- src/app/demo/components/dashboards/candidate/createcandidate2/createcandidate2.component.html
- src/app/demo/components/dashboards/candidate/createcandidate2/createcandidate2.component.spec.ts
- src/app/demo/components/dashboards/candidate/createcandidate2/createcandidate2.component.ts
- src/app/demo/components/dashboards/candidate/createcandidate2/createcandidate2.module.ts
- src/app/demo/components/dashboards/recruiter/recriter.module.ts
- src/app/demo/components/dashboards/recruiter/recruiter.component.html
- src/app/demo/components/dashboards/recruiter/recruiter.component.ts
> popopsrecruiter

- src/app/demo/components/dashboards/candidate/createcandidate/createcandiadte.module.ts
- src/app/demo/components/dashboards/candidate/createcandidate/createcandidate.component.html
- src/app/demo/components/dashboards/menus/menus-routing.module.ts
- src/app/demo/components/dashboards/menus/menus.component.css
- src/app/demo/components/dashboards/menus/menus.component.html
- src/app/demo/components/dashboards/menus/menus.component.ts
- src/app/demo/components/dashboards/menus/menus.module.ts
> candidates steps

- src/app/demo/components/dashboards/menus/menus.component.html
- src/app/demo/components/dashboards/menus/menus.component.ts
- src/app/demo/components/dashboards/menus/menus.module.ts
> candidtaes changes one

- src/app/demo/components/dashboards/menus/menus.component.html
> candidateconfirmfeilds

- src/app/demo/components/dashboards/client/client-routing.module.ts
- src/app/demo/components/dashboards/client/client.component.html
- src/app/demo/components/dashboards/client/client.component.spec.ts
- src/app/demo/components/dashboards/client/client.component.ts
- src/app/demo/components/dashboards/client/client.module.ts
- src/app/demo/components/dashboards/dashboards-routing.module.ts
- src/app/demo/components/dashboards/talentpool/talentpooledit/talentpooledit-routing.module.ts
- src/app/demo/components/dashboards/talentpool/talentpooledit/talentpooledit.component.html
- src/app/demo/components/dashboards/talentpool/talentpooledit/talentpooledit.component.spec.ts
- src/app/demo/components/dashboards/talentpool/talentpooledit/talentpooledit.component.ts
- src/app/demo/components/dashboards/talentpool/talentpooledit/talentpooledit.module.ts
> talentpooleditandclient

- src/app/demo/components/dashboards/talentpool/listtalentpool/listtalentpool.component.html
- src/app/demo/components/dashboards/talentpool/listtalentpool/listtalentpool.component.ts
- src/app/demo/components/dashboards/talentpool/talentpool.component.html
- src/app/demo/components/dashboards/talentpool/talentpool.component.ts
- src/app/demo/components/dashboards/talentpool/talentpooledit/talentpooledit.component.html
- src/app/demo/components/dashboards/talentpool/talentpooledit/talentpooledit.component.ts
talentpooleditpassingobjrouter
> talentpooleditpassingobjrouter

- src/app/demo/components/dashboards/jobs/createjob/createjob.component.html
- src/app/demo/components/dashboards/jobs/createjob/createjob.component.ts
- src/app/demo/components/dashboards/jobs/editjob/editjob.component.html
- src/app/demo/components/dashboards/jobs/editjob/editjob.component.ts
- src/app/demo/components/dashboards/jobs/jobs.component.ts
- src/app/demo/components/dashboards/recruiter/createrecruiter/createrecruiter.component.html
- src/app/demo/components/dashboards/recruiter/createrecruiter/createrecruiter.component.ts
- src/app/demo/components/dashboards/recruiter/editrecruiter/editrecruiter.component.html
- src/app/demo/components/dashboards/recruiter/editrecruiter/editrecruiter.component.ts
- src/app/demo/components/dashboards/recruiter/recruiter.component.html
- src/app/demo/components/dashboards/recruiter/recruiter.component.ts
edit job and recruiter obj passing through router
> edit job and recruiter obj passing through router

- src/app/demo/components/dashboards/candidate/candidate.component.html
- src/app/demo/components/dashboards/candidate/candidate.component.ts
- src/app/demo/components/dashboards/candidate/editcandidate/editcandidate.component.html
- src/app/demo/components/dashboards/candidate/editcandidate/editcandidate.component.ts
- src/app/demo/components/dashboards/menus/menus.component.html
- src/app/demo/components/dashboards/menus/menus.component.ts
> editcandidatepassing obj

- src/app/demo/components/dashboards/home/home.component.html
- src/app/demo/components/dashboards/home/home.component.ts
- src/app/demo/components/dashboards/home/home.module.ts
> dashboard changes

- src/app/demo/components/dashboards/client/createclient/createclient.component.html
- src/app/demo/components/dashboards/client/createclient/createclient.component.ts
- src/app/demo/components/dashboards/client/editclient/editclient.component.html
- src/app/demo/components/dashboards/client/editclient/editclient.component.scss
- src/app/demo/components/dashboards/client/editclient/editclient.component.ts
> clientchangesstyles

- src/app/demo/components/dashboards/candidate/editcandidate/editcandidate.component.ts
- src/app/demo/components/dashboards/menus/menus.component.ts
candidate education exper validtae
> candidate education exper validtae

- src/app/demo/components/dashboards/home/home.component.html
- src/app/demo/components/dashboards/home/home.component.ts
> dashboardchanges

- src/app/demo/components/dashboards/home/home.component.html
- src/app/demo/components/dashboards/home/home.component.ts
>  dashboardclientwithjobs

- src/app/demo/components/dashboards/candidate/editcandidate/editcandidate.component.html
- src/app/demo/components/dashboards/candidate/editcandidate/editcandidate.component.ts
- src/app/demo/components/dashboards/menus/menus.component.html
- src/app/demo/components/dashboards/menus/menus.component.ts
dateofbirth feild chnages candidate
> dateofbirth feild chnages candidate

- src/app/demo/components/dashboards/candidate/editcandidate/editcandidate.component.ts
> candidatechangesdit

- src/app/demo/components/dashboards/home/home.component.html
- src/app/demo/components/dashboards/home/home.component.ts
home compoent job cards changes
> home compoent job cards changes

- src/app/demo/components/dashboards/dashboards-routing.module.ts
- src/app/demo/components/dashboards/vendor/vendor-create/vendor-create-routing.module.ts
- src/app/demo/components/dashboards/vendor/vendor-create/vendor-create.component.html
- src/app/demo/components/dashboards/vendor/vendor-create/vendor-create.component.spec.ts
- src/app/demo/components/dashboards/vendor/vendor-create/vendor-create.component.ts
- src/app/demo/components/dashboards/vendor/vendor-create/vendor-create.module.ts
- src/app/demo/components/dashboards/vendor/vendor-edit/vendor-edit-routing.module.ts
- src/app/demo/components/dashboards/vendor/vendor-edit/vendor-edit.component.html
- src/app/demo/components/dashboards/vendor/vendor-edit/vendor-edit.component.spec.ts
- src/app/demo/components/dashboards/vendor/vendor-edit/vendor-edit.component.ts
- src/app/demo/components/dashboards/vendor/vendor-edit/vendor-edit.module.ts
- src/app/demo/components/dashboards/vendor/vendor-list/vendor-list-routing.module.ts
- src/app/demo/components/dashboards/vendor/vendor-list/vendor-list.component.html
- src/app/demo/components/dashboards/vendor/vendor-list/vendor-list.component.spec.ts
- src/app/demo/components/dashboards/vendor/vendor-list/vendor-list.component.ts
- src/app/demo/components/dashboards/vendor/vendor-list/vendor-list.module.ts
- src/app/demo/components/dashboards/vendor/vendor-routing.module.ts
- src/app/demo/components/dashboards/vendor/vendor.component.html
- src/app/demo/components/dashboards/vendor/vendor.component.spec.ts
- src/app/demo/components/dashboards/vendor/vendor.component.ts
- src/app/demo/components/dashboards/vendor/vendor.module.ts
- src/app/layout/app.menu.component.ts
> vendor component added

- src/app/demo/components/dashboards/vendor/vendor-create/vendor-create.component.ts
> errors in vendor

- src/app/demo/components/dashboards/vendor/vendor-edit/vendor-edit.component.html
- src/app/demo/components/dashboards/vendor/vendor-edit/vendor-edit.component.ts
- src/app/demo/components/dashboards/vendor/vendor-edit/vendor-edit.module.ts
- src/app/demo/components/dashboards/vendor/vendor-list/vendor-list.component.html
- src/app/demo/components/dashboards/vendor/vendor-list/vendor-list.component.ts
> vendor edit

- src/app/demo/components/dashboards/dashboards-routing.module.ts
- src/app/demo/components/dashboards/vendor/vendor-edit/vendor-edit.component.html
- src/app/demo/components/dashboards/vendor/vendor-list/vendor-list.component.html
- src/app/layout/app.menu.component.ts
> vendor issues fixes

- src/app/demo/components/dashboards/loginuser/loginuser.component.ts
- src/app/demo/components/model/permission.ts
- src/app/demo/components/model/role.ts
- src/app/demo/service/auth.service.spec.ts
- src/app/demo/service/auth.service.ts
- src/app/layout/app.layout.module.ts
- src/app/layout/app.menu.component.html
- src/app/layout/app.menu.component.ts
> role based login dyanamic

- src/app/app-routing.module.ts
- src/app/demo/components/dashboards/dashboards-routing.module.ts
- src/app/layout/app.menu.component.html
- src/app/layout/app.menu.component.ts
> rolebasedloginchanges

- src/app/demo/components/dashboards/vendor/vendor-list/vendor-list.component.css
- src/app/demo/components/dashboards/vendor/vendor-list/vendor-list.component.html
- src/app/demo/components/dashboards/vendor/vendor-list/vendor-list.component.ts
- src/app/layout/app.menu.component.ts
> vendor pagination ui

- src/app/demo/components/dashboards/candidate/candidate.component.html
- src/app/demo/components/dashboards/candidate/candidate.component.scss
- src/app/demo/components/dashboards/candidate/candidate.component.ts
- src/app/demo/components/dashboards/client/client.component.css
- src/app/demo/components/dashboards/client/client.component.html
- src/app/demo/components/dashboards/client/client.component.ts
- src/app/demo/components/dashboards/email/email.component.html
- src/app/demo/components/dashboards/email/email.component.scss
- src/app/demo/components/dashboards/email/email.component.ts
- src/app/demo/components/dashboards/jobs/jobs.component.css
- src/app/demo/components/dashboards/jobs/jobs.component.html
- src/app/demo/components/dashboards/jobs/jobs.component.ts
- src/app/demo/components/dashboards/recruiter/recruiter.component.html
- src/app/demo/components/dashboards/recruiter/recruiter.component.scss
- src/app/demo/components/dashboards/recruiter/recruiter.component.ts
- src/app/demo/components/dashboards/talentpool/listtalentpool/listtalentpool.component.html
- src/app/demo/components/dashboards/talentpool/listtalentpool/listtalentpool.component.scss
- src/app/demo/components/dashboards/talentpool/listtalentpool/listtalentpool.component.ts
> cutempaginationuiallcomponnet

- src/app/demo/components/dashboards/candidate/candidate.component.ts
- src/app/demo/components/dashboards/menus/menus.component.ts
- src/app/demo/components/model/candidate.ts
login based candidates list coming
>  login based candidates list coming

- src/app/demo/components/dashboards/candidate/hiringflowactivity/hiringflowactivity-routing.module.ts
- src/app/demo/components/dashboards/candidate/hiringflowactivity/hiringflowactivity.component.css
- src/app/demo/components/dashboards/candidate/hiringflowactivity/hiringflowactivity.component.html
- src/app/demo/components/dashboards/candidate/hiringflowactivity/hiringflowactivity.component.spec.ts
- src/app/demo/components/dashboards/candidate/hiringflowactivity/hiringflowactivity.component.ts
- src/app/demo/components/dashboards/candidate/hiringflowactivity/hiringflowactivity.module.ts
- src/app/demo/components/dashboards/dashboards-routing.module.ts
- src/app/layout/app.menu.component.ts
> HiringflowactivityComponent

- src/app/demo/components/dashboards/candidate/hiringflowactivity/hiringflowactivity.component.css
- src/app/demo/components/dashboards/candidate/hiringflowactivity/hiringflowactivity.component.html
- src/app/demo/components/dashboards/candidate/hiringflowactivity/hiringflowactivity.component.ts
> hiringflowactivityuichanges

- src/app/demo/components/dashboards/dashboards-routing.module.ts
- src/app/demo/components/dashboards/talentpool/talentpoolinactivecandidatelist/talentpoolinactivecandidatelist-routing.module.ts
- src/app/demo/components/dashboards/talentpool/talentpoolinactivecandidatelist/talentpoolinactivecandidatelist.component.css
- src/app/demo/components/dashboards/talentpool/talentpoolinactivecandidatelist/talentpoolinactivecandidatelist.component.html
- src/app/demo/components/dashboards/talentpool/talentpoolinactivecandidatelist/talentpoolinactivecandidatelist.component.spec.ts
- src/app/demo/components/dashboards/talentpool/talentpoolinactivecandidatelist/talentpoolinactivecandidatelist.component.ts
- src/app/demo/components/dashboards/talentpool/talentpoolinactivecandidatelist/talentpoolinactivecandidatelist.module.ts
- src/app/layout/app.menu.component.ts
talentpoolinactivecandidateslist
> talentpoolinactivecandidateslist

- src/app/demo/components/dashboards/talentpool/talentpoolinactivecandidatelist/talentpoolinactivecandidatelist.component.html
> remove unwanted code

- src/app/demo/components/dashboards/candidate/uploadfile/uploadfile-routing.module.ts
- src/app/demo/components/dashboards/candidate/uploadfile/uploadfile.component.html
- src/app/demo/components/dashboards/candidate/uploadfile/uploadfile.component.spec.ts
- src/app/demo/components/dashboards/candidate/uploadfile/uploadfile.component.ts
- src/app/demo/components/dashboards/candidate/uploadfile/uploadfile.module.ts
- src/app/demo/components/dashboards/dashboards-routing.module.ts
- src/app/demo/components/dashboards/jobs/assignjobstovendor/assignjobstovendor-routing.module.ts
- src/app/demo/components/dashboards/jobs/assignjobstovendor/assignjobstovendor.component.html
- src/app/demo/components/dashboards/jobs/assignjobstovendor/assignjobstovendor.component.spec.ts
- src/app/demo/components/dashboards/jobs/assignjobstovendor/assignjobstovendor.component.ts
- src/app/demo/components/dashboards/jobs/assignjobstovendor/assignjobstovendor.module.ts
- src/app/layout/app.menu.component.ts
Assignjobstovendorandfileuplaod component added
> Assignjobstovendorandfileuplaod component added

- src/app/demo/components/dashboards/jobs/assignjobstovendor/assignjobstovendor.component.css
- src/app/demo/components/dashboards/jobs/assignjobstovendor/assignjobstovendor.component.html
- src/app/demo/components/dashboards/jobs/assignjobstovendor/assignjobstovendor.component.ts
- src/app/demo/components/dashboards/jobs/assignjobstovendor/assignjobstovendor.module.ts
- src/app/demo/components/dashboards/jobs/job.service.spec.ts
- src/app/demo/components/dashboards/jobs/job.service.ts
> assignjobstovendotapis

- src/app/demo/components/dashboards/jobs/job.service.ts
> assing jobs changes apis

- src/app/demo/components/dashboards/reports/reports.component.html
> before serivces code added

- src/app/demo/components/dashboards/jobs/createjob/createjob.component.html
- src/app/demo/components/dashboards/jobs/createjob/createjob.component.ts
- src/app/demo/components/dashboards/jobs/editjob/editjob.component.ts
- src/app/demo/components/dashboards/jobs/job.service.ts
- src/app/demo/components/dashboards/jobs/jobs.component.ts
- src/app/demo/components/model/locations1.ts
- src/app/demo/components/model/locations2.ts
>  jobs services added apis

- src/app/demo/components/dashboards/client/client.component.html
- src/app/demo/components/dashboards/client/client.component.ts
- src/app/demo/components/dashboards/client/createclient/createclient.component.ts
- src/app/demo/components/dashboards/client/editclient/editclient.component.ts
- src/app/demo/service/client.service.ts
- src/app/demo/service/vendor.service.ts
> clientservicesadded

- src/app/demo/components/dashboards/email/createemail/createemail.component.ts
- src/app/demo/components/dashboards/email/editemail/editemail.component.ts
- src/app/demo/components/dashboards/email/email.component.ts
- src/app/demo/service/emailtemplateervice.service.spec.ts
- src/app/demo/service/emailtemplateervice.service.ts
> EmailtemplateService

- src/app/demo/components/dashboards/talentpool/edittalentpool/edittalentpool.component.ts
- src/app/demo/components/dashboards/talentpool/listtalentpool/listtalentpool.component.html
- src/app/demo/components/dashboards/talentpool/listtalentpool/listtalentpool.component.ts
- src/app/demo/components/dashboards/talentpool/talentpool.component.ts
- src/app/demo/components/dashboards/talentpool/talentpooledit/talentpooledit.component.ts
- src/app/demo/service/talentpool.service.spec.ts
- src/app/demo/service/talentpool.service.ts
> talentpoolserivcesadded

- src/app/demo/components/dashboards/home/home.component.ts
- src/app/demo/service/home.service.spec.ts
- src/app/demo/service/home.service.ts
- src/environments/environment.prod.ts
- src/environments/environment.ts
> homeservices

- src/app/demo/components/dashboards/loginuser/loginuser.component.ts
- src/app/demo/service/useraccount.service.spec.ts
- src/app/demo/service/useraccount.service.ts
> userservices

- src/app/demo/components/dashboards/candidate/candidate.component.html
- src/app/demo/components/dashboards/candidate/candidate.component.ts
- src/app/demo/components/dashboards/candidate/createcandidate/createcandiadte-routing.module.ts
- src/app/demo/components/dashboards/candidate/createcandidate/createcandiadte.module.ts
- src/app/demo/components/dashboards/candidate/createcandidate/createcandidate.component.html
- src/app/demo/components/dashboards/candidate/createcandidate/createcandidate.component.scss
- src/app/demo/components/dashboards/candidate/createcandidate/createcandidate.component.ts
- src/app/demo/components/dashboards/candidate/createcandidate2/createcandidate2.module.ts
- src/app/demo/components/dashboards/candidate/editcandidate/editcandidate.component.html
- src/app/demo/components/dashboards/candidate/editcandidate/editcandidate.component.ts
- src/app/demo/components/dashboards/candidate/uploadfile/uploadfile.component.ts
- src/app/demo/components/dashboards/menus/menus.module.ts
- src/app/demo/service/candidate.service.spec.ts
- src/app/demo/service/candidate.service.ts
> candidateservices

- src/app/demo/components/dashboards/talentpool/talentpoolinactivecandidatelist/talentpoolinactivecandidatelist.component.ts
- src/app/demo/components/dashboards/vendor/vendor-list/vendor-list.component.ts
- src/app/demo/service/candidate.service.ts
inactivecandidateslistin talentpoll
> inactivecandidateslistin talentpoll

- src/app/demo/components/dashboards/candidate/candidateliststageswise/candidateliststageswise-routing.module.ts
- src/app/demo/components/dashboards/candidate/candidateliststageswise/candidateliststageswise.component.css
- src/app/demo/components/dashboards/candidate/candidateliststageswise/candidateliststageswise.component.html
- src/app/demo/components/dashboards/candidate/candidateliststageswise/candidateliststageswise.component.spec.ts
- src/app/demo/components/dashboards/candidate/candidateliststageswise/candidateliststageswise.component.ts
- src/app/demo/components/dashboards/candidate/candidateliststageswise/candidateliststageswise.module.ts
- src/app/demo/components/dashboards/dashboards-routing.module.ts
- src/app/demo/service/Candidate2.service.spec.ts
- src/app/demo/service/Candidate2.service.ts
- src/app/demo/service/backup.service.spec.ts
- src/app/demo/service/backup.service.ts
- src/app/demo/service/common.service.spec.ts
- src/app/demo/service/common.service.ts
> candidatestagsservcies

- src/app/demo/components/dashboards/candidate/candidate.component.ts
- src/app/demo/components/dashboards/candidate/candidateliststageswise/candidateliststageswise.component.ts
- src/app/demo/components/dashboards/candidate/createcandidate/createcandidate.component.ts
- src/app/demo/components/dashboards/candidate/editcandidate/editcandidate.component.ts
- src/app/demo/components/dashboards/candidate/uploadfile/uploadfile.component.ts
- src/app/demo/components/dashboards/home/home.component.ts
- src/app/demo/components/dashboards/jobs/assignjobstorecruiter/assignjobstorecruiter.component.ts
- src/app/demo/components/dashboards/loginuser/loginuser.component.ts
- src/app/demo/components/dashboards/recruiter/createrecruiter/createrecruiter.component.ts
- src/app/demo/components/dashboards/recruiter/editrecruiter/editrecruiter.component.ts
- src/app/demo/components/dashboards/recruiter/recruiter.component.ts
- src/app/demo/components/dashboards/talentpool/edittalentpool/edittalentpool.component.ts
- src/app/demo/components/dashboards/talentpool/listtalentpool/listtalentpool.component.ts
- src/app/demo/components/dashboards/talentpool/talentpool.component.ts
- src/app/demo/components/dashboards/talentpool/talentpooledit/talentpooledit.component.ts
- src/app/demo/components/dashboards/talentpool/talentpoolinactivecandidatelist/talentpoolinactivecandidatelist.component.ts
- src/app/demo/components/dashboards/vendor/vendor-create/vendor-create.component.ts
- src/app/demo/components/dashboards/vendor/vendor-edit/vendor-edit.component.ts
- src/app/demo/components/dashboards/vendor/vendor-list/vendor-list.component.ts
- src/app/demo/hiring-process-services/Candidate2.service.ts
- src/app/demo/hiring-process-services/backup.service.ts
- src/app/demo/hiring-process-services/candidate.service.ts
- src/app/demo/hiring-process-services/client.service.ts
- src/app/demo/hiring-process-services/common.service.ts
- src/app/demo/hiring-process-services/home.service.ts
- src/app/demo/hiring-process-services/job.service.ts
- src/app/demo/hiring-process-services/recruiter.service.ts
- src/app/demo/hiring-process-services/talentpool.service.ts
- src/app/demo/hiring-process-services/useraccount.service.ts
- src/app/demo/hiring-process-services/vendor.service.ts
> servicesfileadded

- src/app/demo/hiring-process-services/Candidate2.service.ts
- src/app/demo/hiring-process-services/backup.service.ts
- src/app/demo/hiring-process-services/candidate.service.ts
- src/app/demo/hiring-process-services/client.service.ts
- src/app/demo/hiring-process-services/common.service.ts
- src/app/demo/hiring-process-services/job.service.ts
- src/app/demo/hiring-process-services/recruiter.service.ts
- src/app/demo/hiring-process-services/talentpool.service.ts
- src/app/demo/hiring-process-services/useraccount.service.ts
- src/app/demo/hiring-process-services/vendor.service.ts
> addedfileenvironment

- src/app/demo/components/dashboards/candidate/candidate.component.html
- src/app/demo/components/dashboards/candidate/candidate.component.ts
- src/app/demo/hiring-process-services/candidate4.service.ts
> loginbasedcanddiatelistworks

- src/app/demo/components/dashboards/candidate/hiringflowactivity/hiringflowactivity.component.ts
- src/app/demo/hiring-process-services/hiringflowactivity.service.spec.ts
- src/app/demo/hiring-process-services/hiringflowactivity.service.ts
> HiringFlowActivityService

- src/app/demo/components/dashboards/client/client.component.html
> missing add button in client

- src/app/demo/components/dashboards/candidate/createcandidate/createcandidate.component.html
- src/app/demo/components/dashboards/candidate/createcandidate/createcandidate.component.ts
candidate next button issues fix
> candidate next button issues fix

- src/app/demo/components/dashboards/candidate/createcandidate/createcandidate.component.html
- src/app/demo/components/dashboards/candidate/createcandidate/createcandidate.component.ts
> upload resume added ui

- src/app/demo/components/dashboards/candidate/resumeuploader/resumeuploader-routing.module.ts
- src/app/demo/components/dashboards/candidate/resumeuploader/resumeuploader.component.html
- src/app/demo/components/dashboards/candidate/resumeuploader/resumeuploader.component.spec.ts
- src/app/demo/components/dashboards/candidate/resumeuploader/resumeuploader.component.ts
- src/app/demo/components/dashboards/candidate/resumeuploader/resumeuploader.module.ts
- src/app/demo/components/dashboards/dashboards-routing.module.ts
- src/app/layout/app.menu.component.ts
> resumeuplodercomponentadded
